taco:
  orders:
    pageSize: 10
    
spring:
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue
  rabbitmq:
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central
      receive-timeout: 30000
  kafka:
    bootstrap-servers:
    - kafka.tacocloud.com:9092
    - kafka.tacocloud.com:9093
    - kafka.tacocloud.com:9094
    template:
      default-topic: tacocloud.orders.topic