# 리스트 13.5 application.yml에 단일 유레카 서버 구성하기

server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
